services:

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
      - "5556:5555"
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env.docker
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    env_file: .env.docker
    ports:
      - "5433:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db: